name: "MGMLink_PathSearch"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python==3.11.7
  - tqdm==4.67.0
  - gensim==4.3.2
  - numpy==1.26.4
  - scipy==1.13.1
  - pip
  - pip:
    - csrgraph==0.1.28
    - nodevectors==0.1.23
    - igraph==0.11.8
    - py4cytoscape==1.11.0