name: "Cartoomics"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python>=3.8.*
  - tqdm>=4.64.0
  - gensim>=4.2.0
  - numpy>=1.22.4
  - scipy
  - pip
  - pip:
    - csrgraph>=0.1.28
    - nodevectors>=0.1.23
    - igraph>=0.9.10
    - py4cytoscape>=1.3.0
