name: "snakemake"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python==3.11.7
  - tqdm==4.67.0
  - gensim==4.3.2
  - numpy==1.26.4
  - pip
  - pip:
    - csrgraph==0.1.28
    - nodevectors==0.1.23
    - rdflib>=6.2.0
