#This script will convert the triples generated by Convert_Patterns of Subject/Predicate/Object headers to contain brackets.

import pandas as pd
import csv
import argparse

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
#Extract relationships
parser.add_argument("--triples-file",dest="TriplesFile",required=True,help="TriplesFile")
parser.add_argument("--output-dir",dest="OutputDir",required=True,help="OutputDir")

#Generate argument parser and define arguments
args = parser.parse_args()

triples_file = args.TriplesFile
output_dir = args.OutputDir

orig_file = pd.read_csv(triples_file)

orig_file["Subject"] = '<'+orig_file["Subject"]+'>'
orig_file["Predicate"] = '<'+orig_file["Predicate"]+'>'
orig_file["Object"] = '<'+orig_file["Object"]+'>'

filename = triples_file.split('.csv')[0].split('/')[1]

orig_file.to_csv(output_dir + '/' + filename + '_Brackets.txt',sep='\t',index=False)
